package com.viewfunction.messageEngine.exchange.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ActivityTaskNotificationInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ActivityTaskNotificationInfo extends CayenneDataObject {

    public static final String ACTIVITY_ID_PROPERTY = "activityId";
    public static final String ACTIVITY_NAME_PROPERTY = "activityName";
    public static final String NOTIFICATION_ID_PROPERTY = "notificationId";
    public static final String TASK_DESCRIPTION_PROPERTY = "taskDescription";
    public static final String TASK_DUE_DATE_PROPERTY = "taskDueDate";
    public static final String TASK_DUE_STATUS_PROPERTY = "taskDueStatus";
    public static final String TASK_NAME_PROPERTY = "taskName";
    public static final String TASK_ROLE_PROPERTY = "taskRole";

    public static final String INFO_ID_PK_COLUMN = "infoId";

    public void setActivityId(String activityId) {
        writeProperty("activityId", activityId);
    }
    public String getActivityId() {
        return (String)readProperty("activityId");
    }

    public void setActivityName(String activityName) {
        writeProperty("activityName", activityName);
    }
    public String getActivityName() {
        return (String)readProperty("activityName");
    }

    public void setNotificationId(String notificationId) {
        writeProperty("notificationId", notificationId);
    }
    public String getNotificationId() {
        return (String)readProperty("notificationId");
    }

    public void setTaskDescription(String taskDescription) {
        writeProperty("taskDescription", taskDescription);
    }
    public String getTaskDescription() {
        return (String)readProperty("taskDescription");
    }

    public void setTaskDueDate(Date taskDueDate) {
        writeProperty("taskDueDate", taskDueDate);
    }
    public Date getTaskDueDate() {
        return (Date)readProperty("taskDueDate");
    }

    public void setTaskDueStatus(String taskDueStatus) {
        writeProperty("taskDueStatus", taskDueStatus);
    }
    public String getTaskDueStatus() {
        return (String)readProperty("taskDueStatus");
    }

    public void setTaskName(String taskName) {
        writeProperty("taskName", taskName);
    }
    public String getTaskName() {
        return (String)readProperty("taskName");
    }

    public void setTaskRole(String taskRole) {
        writeProperty("taskRole", taskRole);
    }
    public String getTaskRole() {
        return (String)readProperty("taskRole");
    }

}
