package com.viewfunction.messageEngine.exchange.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ExternalResourceNotificationInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExternalResourceNotificationInfo extends CayenneDataObject {

    public static final String NOTIFICATION_ID_PROPERTY = "notificationId";
    public static final String RESOURCE_NAME_PROPERTY = "resourceName";
    public static final String RESOURCE_URL_PROPERTY = "resourceURL";

    public static final String INFO_ID_PK_COLUMN = "infoId";

    public void setNotificationId(String notificationId) {
        writeProperty("notificationId", notificationId);
    }
    public String getNotificationId() {
        return (String)readProperty("notificationId");
    }

    public void setResourceName(String resourceName) {
        writeProperty("resourceName", resourceName);
    }
    public String getResourceName() {
        return (String)readProperty("resourceName");
    }

    public void setResourceURL(String resourceURL) {
        writeProperty("resourceURL", resourceURL);
    }
    public String getResourceURL() {
        return (String)readProperty("resourceURL");
    }

}
