package com.viewfunction.messageEngine.exchange.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Message was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Message extends CayenneDataObject {

    public static final String GROUP_ID_PROPERTY = "groupId";
    public static final String MESSAGE_CONTENT_PROPERTY = "messageContent";
    public static final String MESSAGE_READ_STATUS_PROPERTY = "messageReadStatus";
    public static final String MESSAGE_RECEIVER_ID_PROPERTY = "messageReceiverId";
    public static final String MESSAGE_RECEIVERS_ID_PROPERTY = "messageReceiversId";
    public static final String MESSAGE_RECEIVERS_NAME_PROPERTY = "messageReceiversName";
    public static final String MESSAGE_RECEIVERS_TYPE_PROPERTY = "messageReceiversType";
    public static final String MESSAGE_SCOPE_PROPERTY = "messageScope";
    public static final String MESSAGE_SENDER_ID_PROPERTY = "messageSenderId";
    public static final String MESSAGE_SENDER_NAME_PROPERTY = "messageSenderName";
    public static final String MESSAGE_SENT_DATE_PROPERTY = "messageSentDate";
    public static final String MESSAGE_TITLE_PROPERTY = "messageTitle";

    public static final String MESSAGE_ID_PK_COLUMN = "messageId";

    public void setGroupId(String groupId) {
        writeProperty("groupId", groupId);
    }
    public String getGroupId() {
        return (String)readProperty("groupId");
    }

    public void setMessageContent(String messageContent) {
        writeProperty("messageContent", messageContent);
    }
    public String getMessageContent() {
        return (String)readProperty("messageContent");
    }

    public void setMessageReadStatus(Boolean messageReadStatus) {
        writeProperty("messageReadStatus", messageReadStatus);
    }
    public Boolean getMessageReadStatus() {
        return (Boolean)readProperty("messageReadStatus");
    }

    public void setMessageReceiverId(String messageReceiverId) {
        writeProperty("messageReceiverId", messageReceiverId);
    }
    public String getMessageReceiverId() {
        return (String)readProperty("messageReceiverId");
    }

    public void setMessageReceiversId(String messageReceiversId) {
        writeProperty("messageReceiversId", messageReceiversId);
    }
    public String getMessageReceiversId() {
        return (String)readProperty("messageReceiversId");
    }

    public void setMessageReceiversName(String messageReceiversName) {
        writeProperty("messageReceiversName", messageReceiversName);
    }
    public String getMessageReceiversName() {
        return (String)readProperty("messageReceiversName");
    }

    public void setMessageReceiversType(String messageReceiversType) {
        writeProperty("messageReceiversType", messageReceiversType);
    }
    public String getMessageReceiversType() {
        return (String)readProperty("messageReceiversType");
    }

    public void setMessageScope(String messageScope) {
        writeProperty("messageScope", messageScope);
    }
    public String getMessageScope() {
        return (String)readProperty("messageScope");
    }

    public void setMessageSenderId(String messageSenderId) {
        writeProperty("messageSenderId", messageSenderId);
    }
    public String getMessageSenderId() {
        return (String)readProperty("messageSenderId");
    }

    public void setMessageSenderName(String messageSenderName) {
        writeProperty("messageSenderName", messageSenderName);
    }
    public String getMessageSenderName() {
        return (String)readProperty("messageSenderName");
    }

    public void setMessageSentDate(Date messageSentDate) {
        writeProperty("messageSentDate", messageSentDate);
    }
    public Date getMessageSentDate() {
        return (Date)readProperty("messageSentDate");
    }

    public void setMessageTitle(String messageTitle) {
        writeProperty("messageTitle", messageTitle);
    }
    public String getMessageTitle() {
        return (String)readProperty("messageTitle");
    }

}
